// Code generated by Kitex v0.5.2. DO NOT EDIT.

package loginservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	usersrv "myWeb/kitex_gen/user/usersrv"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	EmailLogin(ctx context.Context, Req *usersrv.EmailLoginRequest, callOptions ...callopt.Option) (r *usersrv.EmailLoginResponse, err error)
	SendEmail(ctx context.Context, Req *usersrv.SendEmailRequest, callOptions ...callopt.Option) (r *usersrv.SendEmailResponse, err error)
	UsernamePasswordLogin(ctx context.Context, Req *usersrv.UsernamePasswordLoginRequest, callOptions ...callopt.Option) (r *usersrv.UsernamePasswordLoginResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kLoginServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLoginServiceClient struct {
	*kClient
}

func (p *kLoginServiceClient) EmailLogin(ctx context.Context, Req *usersrv.EmailLoginRequest, callOptions ...callopt.Option) (r *usersrv.EmailLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EmailLogin(ctx, Req)
}

func (p *kLoginServiceClient) SendEmail(ctx context.Context, Req *usersrv.SendEmailRequest, callOptions ...callopt.Option) (r *usersrv.SendEmailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendEmail(ctx, Req)
}

func (p *kLoginServiceClient) UsernamePasswordLogin(ctx context.Context, Req *usersrv.UsernamePasswordLoginRequest, callOptions ...callopt.Option) (r *usersrv.UsernamePasswordLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UsernamePasswordLogin(ctx, Req)
}
