// Code generated by Kitex v0.5.2. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	userInfo "myWeb/kitex_gen/userInfo"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UpdateUser(ctx context.Context, Req *userInfo.UpdateUserRequest, callOptions ...callopt.Option) (r *userInfo.UpdateUserResponse, err error)
	ChangePassword(ctx context.Context, Req *userInfo.ChangePasswordRequest, callOptions ...callopt.Option) (r *userInfo.ChangePasswordResponse, err error)
	GetUser(ctx context.Context, Req *userInfo.GetUserRequest, callOptions ...callopt.Option) (r *userInfo.GetUserResponse, err error)
	RestPassword(ctx context.Context, Req *userInfo.ResetPasswordRequest, callOptions ...callopt.Option) (r *userInfo.ResetPasswordResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) UpdateUser(ctx context.Context, Req *userInfo.UpdateUserRequest, callOptions ...callopt.Option) (r *userInfo.UpdateUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUser(ctx, Req)
}

func (p *kUserServiceClient) ChangePassword(ctx context.Context, Req *userInfo.ChangePasswordRequest, callOptions ...callopt.Option) (r *userInfo.ChangePasswordResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePassword(ctx, Req)
}

func (p *kUserServiceClient) GetUser(ctx context.Context, Req *userInfo.GetUserRequest, callOptions ...callopt.Option) (r *userInfo.GetUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, Req)
}

func (p *kUserServiceClient) RestPassword(ctx context.Context, Req *userInfo.ResetPasswordRequest, callOptions ...callopt.Option) (r *userInfo.ResetPasswordResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RestPassword(ctx, Req)
}
